const getCapabilitiesXml = () => {
  return /*xml*/ `
    <?xml version="1.0" encoding="UTF-8"?>
    <llsd>
      <array>
        <string>AbuseCategories</string>
        <string>AcceptFriendship</string>
        <string>AcceptGroupInvite</string>
        <string>AgentPreferences</string>
        <string>AgentState</string>
        <string>AttachmentResources</string>
        <string>AvatarPickerSearch</string>
        <string>AvatarRenderInfo</string>
        <string>CharacterProperties</string>
        <string>ChatSessionRequest</string>
        <string>CopyInventoryFromNotecard</string>
        <string>CreateInventoryCategory</string>
        <string>DeclineFriendship</string>
        <string>DeclineGroupInvite</string>
        <string>DispatchRegionInfo</string>
        <string>DirectDelivery</string>
        <string>EnvironmentSettings</string>
        <string>EstateAccess</string>
        <string>EstateChangeInfo</string>
        <string>EventQueueGet</string>
        <string>ExtEnvironment</string>
        <string>FetchLib2</string>
        <string>FetchLibDescendents2</string>
        <string>FetchInventory2</string>
        <string>FetchInventoryDescendents2</string>
        <string>IncrementCOFVersion</string>
        <string>GetDisplayNames</string>
        <string>GetExperiences</string>
        <string>AgentExperiences</string>
        <string>FindExperienceByName</string>
        <string>GetExperienceInfo</string>
        <string>GetAdminExperiences</string>
        <string>GetCreatorExperiences</string>
        <string>ExperiencePreferences</string>
        <string>GroupExperiences</string>
        <string>UpdateExperience</string>
        <string>IsExperienceAdmin</string>
        <string>IsExperienceContributor</string>
        <string>InventoryAPIv3</string>
        <string>RegionExperiences</string>
        <string>ExperienceQuery</string>
        <string>GetMetadata</string>
        <string>GetObjectCost</string>
        <string>GetObjectPhysicsData</string>
        <string>GroupAPIv1</string>
        <string>GroupMemberData</string>
        <string>GroupProposalBallot</string>
        <string>HomeLocation</string>
        <string>LandResources</string>
        <string>LSLSyntax</string>
        <string>MapLayer</string>
        <string>MapLayerGod</string>
        <string>MeshUploadFlag</string>
        <string>NavMeshGenerationStatus</string>
        <string>NewFileAgentInventory</string>
        <string>ObjectAnimation</string>
        <string>ObjectMedia</string>
        <string>ObjectMediaNavigate</string>
        <string>ObjectNavMeshProperties</string>
        <string>ParcelPropertiesUpdate</string>
        <string>ParcelVoiceInfoRequest</string>
        <string>ProductInfoRequest</string>
        <string>ProvisionVoiceAccountRequest</string>
        <string>ReadOfflineMsgs</string>
        <string>RemoteParcelRequest</string>
        <string>RenderMaterials</string>
        <string>RequestTextureDownload</string>
        <string>ResourceCostSelected</string>
        <string>RetrieveNavMeshSrc</string>
        <string>SearchStatRequest</string>
        <string>SearchStatTracking</string>
        <string>SendPostcard</string>
        <string>SendUserReport</string>
        <string>SendUserReportWithScreenshot</string>
        <string>ServerReleaseNotes</string>
        <string>SetDisplayName</string>
        <string>SimConsoleAsync</string>
        <string>SimulatorFeatures</string>
        <string>StartGroupProposal</string>
        <string>TerrainNavMeshProperties</string>
        <string>TextureStats</string>
        <string>UntrustedSimulatorMessage</string>
        <string>UpdateAgentInformation</string>
        <string>UpdateAgentLanguage</string>
        <string>UpdateAvatarAppearance</string>
        <string>UpdateGestureAgentInventory</string>
        <string>UpdateGestureTaskInventory</string>
        <string>UpdateNotecardAgentInventory</string>
        <string>UpdateNotecardTaskInventory</string>
        <string>UpdateScriptAgent</string>
        <string>UpdateScriptTask</string>
        <string>UpdateSettingsAgentInventory</string>
        <string>UpdateSettingsTaskInventory</string>
        <string>UploadBakedTexture</string>
        <string>UserInfo</string>
        <string>ViewerAsset</string>
        <string>ViewerBenefits</string>
        <string>ViewerMetrics</string>
        <string>ViewerStartAuction</string>
        <string>ViewerStats</string>
      </array>
    </llsd>
  `.trim();
};

export default getCapabilitiesXml;
